import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars for SealMetrics Docs
 * Organized by product areas: Getting Started, Reports, Privacy, API, FAQ, Changelog.
 */

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'intro' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reports',
      link: { type: 'doc', id: 'getting-started/reports/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started/reports',
        },
      ],
    },
    {
      type: 'category',
      label: 'First Steps',
      link: { type: 'doc', id: 'first-steps/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'first-steps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Privacy & Consentless Analytics',
      link: { type: 'doc', id: 'privacy-and-consentless/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'privacy-and-consentless',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/overview' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      link: { type: 'doc', id: 'faq/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        },
      ],
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
  ],
};

export default sidebars;